### Add a portfolio
POST http://{{host}}:{{port}}/api/v1/portfolio?name=Portfolio&horizon=2022-04-13&broker=SBER

### Add an operation with a new position and equity



### Add an operation

### Add a dividend
