###
POST http://{{host}}:{{port}}/api/v1/portfolio?name=Portfolio&horizon=2022-04-13&broker=SBER

//> {% client.global.set("portfolioId", response.body.json.id) %}

<> 2021-04-13T204436.200.json

###
GET http://{{host}}:{{port}}/api/v1/portfolio

<> 2021-04-13T201836.200.json

###
GET http://{{host}}:{{port}}/api/v1/portfolio/4028b88179abe8f80179abfd0a590007

<> 2021-04-13T204520.200.json

###
DELETE http://{{host}}:{{port}}/api/v1/portfolio/4028b88179abe8f80179abeb8b7e0000

<> 2021-04-13T204407.500.json

###
PUT http://{{host}}:{{port}}/api/v1/portfolio/4028b88179abe8f80179abee06480002/status

<> 2021-04-13T202218.500.json

###
PUT http://{{host}}:{{port}}/api/v1/portfolio/{{id}}
